### ISSUE TITLE
Adding rotation for the screen

### ISSUE THREAD

**Issue by DuyTrandeLion** [afiskon/stm32-ssd1306#10]
Hello,

I would like to add rotation for the screen such as 0 degree, 90 degrees, 180 degrees. 270 degrees. Where can I modify? 

Thanks and best regards,
        Duy

**Comment by afiskon** [comment]
Hello,

Currently you can do it by defining `SSD1306_MIRROR_HORIZ` and `SSD1306_MIRROR_VERT` macros, see https://github.com/afiskon/stm32-ssd1306/blob/master/examples/spi/stm32f4/Makefile#L127 and https://github.com/afiskon/stm32-ssd1306/blob/master/ssd1306/ssd1306.c#L76

If you want to rotate the image in runtime feel free to submit a corresponding pull request.
