### ISSUE TITLE
Wrong comparism in ssd1306_WriteChar

### ISSUE THREAD

**Issue by jago85** [afiskon/stm32-ssd1306#16]
https://github.com/afiskon/stm32-ssd1306/blob/cf755154e3b8e7e0b806fa90f677ee0dbfa654cb/ssd1306/ssd1306.c#L191-L196

I think both "<=" must be only "<". 

E.g. if you where on line 57 on a screen with 64 lines and wanted to print a 7 pixels high character: Line 57 to line 63 are exactly the 7 lines you'd need, but the check would fail because _64 <= (57 + 7)_ is true. The last line to use would always be _SSD1306.CurrentY + Font.FontHeight - 1_

You could even omit the check, because _ssd1306_DrawPixel()_ checks it again. So you could have partial letters on the screen if you wanted to.

P.S.: Thank you for your work with this library.  It worked on the first try with my STM32F401RE.

**Comment by afiskon** [comment]
I believe you are right. Fixed, thanks!
