### ISSUE TITLE
Also works with STM32F0

### ISSUE THREAD

**Issue by et17019** [afiskon/stm32-ssd1306#19]
Tested it with a STM32F030R8 on a nucleo board using I2C.
Just `#include "stm32f0xx_hal.h"` in the ssd1306.h header and be sure to use 4,7k Ohm pullup resistors on the two data wires.

**Comment by afiskon** [comment]
Many thanks for testing the library with STM32F0. Corresponding changes were made in https://github.com/afiskon/stm32-ssd1306/commit/cdb37ce616a0969db2a6874eca18e5cb41d950d2 and https://github.com/afiskon/stm32-ssd1306/commit/7c4e90b8a2f395ea3c607ccbb1422c7a8b5fac98
