### ISSUE TITLE
Fonts 

### ISSUE THREAD

**Issue by gc9n** [afiskon/stm32-ssd1306#3]
Hey  Guys ,
IS there any program to generate fonts ,  i want to import a custom font that i want, is this possible??

**Comment by afiskon** [comment]
Hello,

The fonts were borrowed from another (MIT licensed) library https://github.com/4ilo/ssd1306-stm32HAL I don't know what software what used to create them. Personally I would probably write a little script in Python.

**Comment by afiskon** [comment]
There is a font generator developed by @the-this-pointer https://github.com/the-this-pointer/glcd-font-calculator

At the moment of writing only Windows is supported.

**Comment by afiskon** [comment]
A tutorial about creating custom fonts was added: https://github.com/afiskon/stm32-ssd1306/tree/master/examples/custom-fonts
