### ISSUE TITLE
Port to Maxim 326x

### ISSUE THREAD

**Issue by sjenyart** [afiskon/stm32-ssd1306#32]
I am working on a port to another ARM platform (Maxim 326x) and have integrated with the Maxim I2C library.  Coms look good and the OLED is ACKing but I am not seeing any activity on the display.  

I've tried a number of the tests (after init) with no success.  If anyone has a suggestion on what I might want to tweak on the default init and tests, I am open to suggestions.

Thanks!

**Comment by afiskon** [comment]
I'm sorry but I'm closing this issue, because of the lack of activity and also since it's not an issue in the library.
