### ISSUE TITLE
SSD1309 Support 

### ISSUE THREAD

**Issue by DrunkenMastah** [afiskon/stm32-ssd1306#38]
It's a really silly question but I would like to ask anyway. The ReadMe.md claims that the library supports other drivers except ssd1306 (and specifically ssd1309).Though when I opened ssd1306_conf_template.h it doesn't seem to have any other option for other drivers I also show this suggested project https://github.com/DuyTrandeLion/nrf52-ssd1309 , but this has nothing to do with my toolchain as I use CubeMx and a Nucleo (like the examples here).Again I know it is a silly question as the library is literally named stm32-**ssd1306** thank you in advance.

**Comment by afiskon** [comment]
SSD1309 is compatible with SSD1306, this is why no additional configuration is needed.

Here is an SSD1309 display I'm using for testing:

![img1](https://afiskon.ru/public/ssd1306/IMG_1195.JPG)

![img2](https://afiskon.ru/public/ssd1306/IMG_1197.JPG)

This being said I have only one such display. If you have any issues with particular device please fill the bug and we will figure this out.

Meanwhile I changed README a little https://github.com/afiskon/stm32-ssd1306/commit/e011d915c261285a848c5be3efe5fc2e8600c5a3 Hopefully it describes the situation better now.
