### ISSUE TITLE
Testing on STM32L1

### ISSUE THREAD

**Issue by Teastan0** [afiskon/stm32-ssd1306#40]
Hello, i am tested this library on STM32L1. Function ```ssd1306_TestAll();``` worked successfully. 

I am added ``` #elif defined(STM32L1)
#include "stm32l1xx_hal.h" ``` in **ssd1306.h** and ```#define STM32L1``` in **ssd1306_conf.h**

**Comment by afiskon** [comment]
Hi @Teastan0!

Thanks for letting me know. If it's not too much trouble could you please submit a corresponding pull request? If not that's fine, I will make corresponding changes myself, just a bit later.
