### ISSUE TITLE
Smaller bitmap images not working

### ISSUE THREAD

**Issue by SuriyaMeras** [afiskon/stm32-ssd1306#46]
I have added a bitmap draw function from adafruit library to this library when I used 128 * 64 size bitmap image evrything is fine but when I rescale it to 36 * 36 the iamge is not properly shown. 

```
void ssd1306_DrawBitmap(int16_t x, int16_t y, const unsigned char* bitmap, int16_t width, int16_t height, uint16_t color){
  int16_t byteWidth = (width + 7) / 8; // Bitmap scanline pad = whole byte
  uint8_t byte = 0;

  for(int16_t j=0; j < height; j++, y++){
    for(int16_t i=0; i < width; i++){
      if(i & 7)
       byte <<= 1;
      else
       byte = bitmap[j * byteWidth + i / 8];
      
      if(byte & 0x80)
        ssd1306_DrawPixel(x+i, y, color);
    }
  }
}
```

**Comment by afiskon** [comment]
I'm very sorry, but this an issue tracker, not a forum. Please address your question to [StackOverflow](https://stackoverflow.com/) or a similar platform.
