### ISSUE TITLE
hi, 

### ISSUE THREAD

**Issue by leesohaeng** [afiskon/stm32-ssd1306#52]
Hi
I am honored to use your code.

There is a problem with the ssd1306 test. 
I used your ssd3606 sample code and connected the ssd1306 using SPI. 
The code runs almost perfectly on SSD1306. 
However, there is always a vertical line on the right side of the screen. 

Any code fixes?
![ssd1306](https://user-images.githubusercontent.com/16987981/145678684-23d8d081-ea47-4531-ac6b-46dd528b15be.png)

**Comment by afiskon** [comment]
@leesohaeng hi! Try changing SSD1306_WIDTH as described [here](https://github.com/afiskon/stm32-ssd1306/blob/master/ssd1306/ssd1306_conf_template.h#L51) and re-compiling everything. Let me know if it helps.

**Comment by leesohaeng** [comment]
> 
Hi
Solved. And I changed the starting position of x to 2 in some places.
Thank you very much for your help.
![ssd1306_2](https://user-images.githubusercontent.com/16987981/145697925-838e4556-23ed-4dbc-8b64-3158cb51c39b.png)
