### ISSUE TITLE
How to convert fonts to 16bits ?

### ISSUE THREAD

**Issue by cttneden** [afiskon/stm32-ssd1306#53]
May I ask what software did you use to convert the font to 16bits format?
code as shown below：
==============================================================
static const uint16_t Font7x10 [] = {
0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,  // sp
0x1000, 0x1000, 0x1000, 0x1000, 0x1000, 0x1000, 0x0000, 0x1000, 0x0000, 0x0000,  // !
0x2800, 0x2800, 0x2800, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,  // "
0x2400, 0x2400, 0x7C00, 0x2400, 0x4800, 0x7C00, 0x4800, 0x4800, 0x0000, 0x0000,  // #
0x3800, 0x5400, 0x5000, 0x3800, 0x1400, 0x5400, 0x5400, 0x3800, 0x1000, 0x0000,  // $
================================================================

**Comment by afiskon** [comment]
Sorry, this question duplicates https://github.com/afiskon/stm32-ssd1306/issues/3

**Comment by cttneden** [comment]
Hi, afiskon:
Thanks for your reply.

________________________________
寄件者: Aleksander Alekseev ***@***.***>
寄件日期: 2022年1月27日 下午 03:56
收件者: afiskon/stm32-ssd1306 ***@***.***>
副本: cttneden ***@***.***>; Author ***@***.***>
主旨: Re: [afiskon/stm32-ssd1306] [Duplicate] How to convert fonts to 16bits ? (Issue #53)


Sorry, this question duplicates #3<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fafiskon%2Fstm32-ssd1306%2Fissues%2F3&data=04%7C01%7C%7C9f537625d32a475d0e4a08d9e16a8abf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788669997628338%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iRl5zHNYTQIZUHxlbNh2r%2FYwrnlYR7hYnrsDLXSjL3w%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fafiskon%2Fstm32-ssd1306%2Fissues%2F53%23issuecomment-1022940205&data=04%7C01%7C%7C9f537625d32a475d0e4a08d9e16a8abf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788669997628338%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Mh1JfeCUZ0DZGOuEcRR0C8b%2F%2BeXeosK%2FN0Br50djbEY%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARCMNB4DVMPBCCZ2QAHRWZ3UYD3DHANCNFSM5M4WMSTA&data=04%7C01%7C%7C9f537625d32a475d0e4a08d9e16a8abf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788669997628338%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yLsZ4euh9umDg07ObrzSPMh5ypnZXgrmVcr4LYxPmO8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C9f537625d32a475d0e4a08d9e16a8abf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788669997628338%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2C3satVdaIuTaf7Gl77Gk6yzzDpO4ZVStd8xqlmxL20%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C9f537625d32a475d0e4a08d9e16a8abf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637788669997628338%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vIDmJnfGRdG5nypL7D96IceWbKWqjPf9EoH2Yqma4W8%3D&reserved=0>.
