### ISSUE TITLE
Pull requests are not open : add compatibility for STM32L053

### ISSUE THREAD

**Issue by Corruped** [afiskon/stm32-ssd1306#6]
so I can add compatibility for those MCUs 

(basicly
 #elif defined(STM32L053xx)
#include "stm32l0xx_hal.h"
#endif

into SSD1306.h

**Comment by afiskon** [comment]
Hello @Corruped 

I'm pretty sure that I didn't disable pull requests for this repository. Are you sure?

**Comment by afiskon** [comment]
@Corruped  Sorry but I have to close this issue. Here is an example of a pull request created not a long time ago https://github.com/afiskon/stm32-ssd1306/pull/7

Still if you have any difficulties with submitting a pull request please inform me and we will figure this out.
