### ISSUE TITLE
use screen as portrait mode ?

### ISSUE THREAD

**Issue by zOzBaSHa** [afiskon/stm32-ssd1306#62]
is there a way to use the screen in portrait mode not landscape mode ?

**Comment by afiskon** [comment]
@zOzBaSHa From the library perspective there is no much difference between these two modes. It's up to the programmer to decide what is going to be considered a top of the screen and what is going to be a bottom.

Rendering a text vertically is not implemented though. A patch that implements something like `ssd1306_WriteStringVertically()` would be much appreciated.
