### ISSUE TITLE
Support for STM32WB55 (Nucleo-WB55RG) family

### ISSUE THREAD

**Issue by Viech83** [afiskon/stm32-ssd1306#63]
Hello,

it is my first STM32 project and have the Nucleo-WB55RG board.
Would it be possible the you insert the STM32WB family ?

would be great !!

Kind Regards,

**Comment by afiskon** [comment]
I *think* the library should work just fine with this development board but I don't have the board in order to actually check this.

**Comment by afiskon** [comment]
Could you please modify ssd1306.h accordingly https://github.com/afiskon/stm32-ssd1306/blob/master/ssd1306/ssd1306.h#L18 and confirm that the library is compatible? If it is feel free submitting a corresponding pull request.

**Comment by afiskon** [comment]
Closing the issue due to inactivity and since there is no issue to address.
