### ISSUE TITLE
Support for STM32C0XX Series MCU 

### ISSUE THREAD

**Issue by numberman2000** [afiskon/stm32-ssd1306#66]
First, I'm not familiar with the 'how to' of doing a pull request, as I'm not at all familiar with github, and I don't want to remotely come close to breaking anything. I'm hoping this is proper venue for this.

The STM32C0XX Series is the latest low-cost line of MCU from ST. I got the SPI interface working by adding the following to the header files.

In the ssd1306_conf.h you can add this to the list of MCU #define list

#define STM32C0

and in ssd1306.h the following can be added at the end of the MCU choices

#elif defined(STM32C0)
#include "stm32c0xx_hal.h"

and aside from realizing you need to _start_ with the reset/DC/CS pins high, it worked without a problem.

**Comment by afiskon** [comment]
Thanks for letting us know!

I'm closing the issue since there is no actual issue to fix. If you want to propose changes please send a pull request. There is plenty information online on how to do this.
