### ISSUE TITLE
Files distributed without permission

### ISSUE THREAD

**Issue by stephenkilbaneadi** [afiskon/stm32-ssd1306#74]
These two files contain a license text which disallows distribution in source form, so they should not be included in this repo (or any other):

* examples/oled-tester/firmware/i2c/STM32F411RETx_FLASH.ld
* examples/oled-tester/firmware/spi/STM32F411RETx_FLASH.ld

**Comment by afiskon** [comment]
Thanks, but I honestly don't care.
