### ISSUE TITLE
How to Add Degree Celsius Symbol °C

### ISSUE THREAD

**Issue by asking23** [afiskon/stm32-ssd1306#87]
How to Add Degree Celsius Symbol ? not getting any clue. need to add Degree Celcius.°C

**Comment by afiskon** [comment]
Please read README.

**Comment by kossnikita** [comment]
Small hint from me. You can use `generate.py` with `--charset` argument to introduce your own charset to generated font.

For example

**charset.txt**

```plain
 !"°C%&'()*+,-./0123456789:;<=>?
```

And run

```bash
./generate.py -f arial.txt -s 18 --charset charset.txt
```

It replaces `#` with `°` and `$` with `C`. Then just use this in code

```c
sprintf(buf, "%u#$", temperature); // #$ means °C
```

**Comment by asking23** [comment]
Thanks aton..!!
