### ISSUE TITLE
Cyrillic symbols

### ISSUE THREAD

**Issue by wand031oe** [afiskon/stm32-ssd1306#90]
Hello sir, thank you for your work! I would like to know if there is a chance you could add cyrillic symbols to your library? Or how can I do it myself?

**Comment by kossnikita** [comment]
See https://github.com/afiskon/stm32-ssd1306/issues/87

**Comment by afiskon** [comment]
I don't have interest in maintaining any symbols but Latin. For Cyrillic, Chinese, Japanese etc please see https://github.com/afiskon/stm32-ssd1306/tree/master/examples/custom-fonts and create your own fork.
