### ISSUE TITLE
ssd1309 driver problems

### ISSUE THREAD

**Issue by oppenheim14** [afiskon/stm32-ssd1306#92]
hi guys 
I use ssd1309 screen but not working as expected
https://youtube.com/shorts/LvoIZckszkc

**Comment by afiskon** [comment]
I'm sorry, this is not a support forum.

If you see a particular bug in the code please consider submitting a pull request.

In your video I see you are using jumper wires and the prototyping board. This arrangement can't guarantee a decent contact on high frequencies. Consider soldering the wires.

Good luck!
